server:
  port: 80
github:
  client:
    id: d7a2dd53de6f2e1ebee4
    secret: 7c9ceba827d3326542a7f87b65a939a8891778d0
  redirect:
    uri: http://47.112.152.213/githubCallback
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
        cache: false
  devtools:
    restart:
      enabled: true  #设置开启热部署

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.cwj.conmmunity.mapper
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
community:
  page:
    pageSize: 10

oss:
  endpoint:
    oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4Fr3iioRYy8hDnmhenee
  bucketName: chebweijun
  accessKeySecret: bPrk5CYi1NcYWJoAXhyoEdxCXd7D1z
email:
  account: chenweijun_yz@163.com
  password: 123456cwj
  host: 220.181.12.15
site:
  main:
    title: FreeMI
logging:
  level:
    root: info