server:
  port: 80
github:
  client:
    id: d7a2dd53de6f2e1ebee4
    secret: 7c9ceba827d3326542a7f87b65a939a8891778d0
  redirect:
    uri: http://www.freemi.cn/githubCallback
qq:
  client:
    id: 101852364
    secret: c94af99560e04bebc09a214775bb4da5
  redirect:
    uri: http://www.freemi.cn/qqCallback
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
        cache: false
  devtools:
    restart:
      enabled: true  #设置开启热部署
#  redis:
#    database: 0
#      timeout: 0
#      # Redis服务器地址
#      host: 127.0.0.1
#      # Redis服务器连接端口
#      port: 6379
#      # 连接池最大连接数（使用负值表示没有限制）
#      pool:
#      max-active: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池中的最小空闲连接
#        min-idle: 0

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.cwj.conmmunity.mapper
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
community:
  page:
    pageSize: 10

oss:
  endpoint:
    oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4Fr3iioRYy8hDnmhenee
  bucketName: chebweijun
  accessKeySecret: bPrk5CYi1NcYWJoAXhyoEdxCXd7D1z
email:
  account: chenweijun_yz@163.com
  password: 123456cwj
  host: smtp.163.com
site:
  main:
    title: FreeMI

logging:
  level:
    root: info