server:
  port: 80
github:
  client:
    id: d7a2dd53de6f2e1ebee4
    secret: 7c9ceba827d3326542a7f87b65a939a8891778d0
  redirect:
    uri: http://www.freemi.cn/githubCallback
qq:
  client:
    id: 101852364
    secret: c94af99560e04bebc09a214775bb4da5
  redirect:
    uri: http://www.freemi.cn/qqCallback
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://127.0.0.1:3306/community?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化连接池个数
    initialSize: 5
    # 最小连接池个数——》已经不再使用，配置了也没效果
    minIdle: 2
    # 最大连接池个数
    maxActive: 20
    # 配置获取连接等待超时的时间，单位毫秒，缺省启用公平锁，并发效率会有所下降
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 用来检测连接是否有效的sql，要求是一个查询语句。
    # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用
    validationQuery: SELECT 1 FROM DUAL
    # 建议配置为true，不影响性能，并且保证安全性。
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 通过别名的方式配置扩展插件，多个英文逗号分隔，常用的插件有：
    # 监控统计用的filter:stat
    # 日志用的filter:log4j
    # 防御sql注入的filter:wall
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  thymeleaf:
        cache: false
  devtools:
    restart:
      enabled: true  #设置开启热部署

  redis :
    host : localhost
    port : 6379
    database : 0
    jedis:
      pool:
        #连接池中的最大空闲连接
        max-idle : 8
        #连接池中的最小空闲连接
        min-idle : 1
        #连接池最大连接数（使用负值表示没有限制）
        max-active : 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait : -1
    timeout: 5000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.cwj.conmmunity.mapper
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
community:
  page:
    pageSize: 10

oss:
  endpoint:
    oss-cn-shenzhen.aliyuncs.com
  accessKeyId: LTAI4Fr3iioRYy8hDnmhenee
  bucketName: chebweijun
  accessKeySecret: bPrk5CYi1NcYWJoAXhyoEdxCXd7D1z
site:
  main:
    title: FreeMI

logging:
  level:
    root: info

mail:
  smtp:
    auth: true
    port: 465
    timeout: 5000
  transport:
    protocol: smtp
  send:
    charset: UTF-8
  is:
    ssl: true
  host: smtp.163.com
  auth:
    name: chenweijun_yz@163.com
    password: 123456cwj

